# .travis.yml
language: node_js
dist: xenial
sudo: required

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: '12'
      env: KNEX_TEST_TIMEOUT=60000 MYSQL_URL=mysql://root:testrootpassword@localhost:23306/ PG_URL=postgres://testuser:testpassword@localhost:25432/
install:
  - yarn install --frozen-lockfile
  # - (echo $DB | grep oracledb) && npm install oracledb || true

before_script:
  - yarn db:start
  - docker-compose -f scripts/docker-compose.yml exec mysql bash -c 'echo "CREATE DATABASE test1" | mysql -uroot -ptestrootpassword'
  - docker-compose -f scripts/docker-compose.yml exec mysql bash -c 'echo "CREATE DATABASE test2" | mysql -uroot -ptestrootpassword'
  # populate them with data
  - yarn db-build

script:
  - yarn typecheck
  - yarn lint
  - export DEBUG=join-monster
  - yarn testmysql-paging

after_success:
  - npm run coveralls

notifications:
  email: false

services:
  - docker